### ISSUE TITLE
robot_description namespacing is inconsistent

### ISSUE THREAD

**Issue by kruusamae** [robotont/robotont_description#12]
the robot description is uploaded to param.server without adding robotont ns. when working with gazebo almost always, the robotont namespace is added. this causes confusion and bugs, of course.

@RValner @Veix123 what would be the better solution here, to namespace or not to namespace?

whichever way we go, i would propose we have a launch-file per description package that uploads the robot description into param server. every other package and launch-file simply uses that launch-file, thus eliminating inconsistencies between packages. universal robots is doing this already, https://github.com/ros-industrial/universal_robot/blob/kinetic-devel/ur_description/launch/ur3_upload.launch

**Comment by RValner** [comment]
i am always pro-namespacing. the second you add andother robot into the mix, things blow up because of a missing namespace (or globally outlined topic names). the launch-file idea also makes sense.

**Comment by Veix123** [comment]
+1 for namespacing. Nevertheless, we have to keep in mind that namespaces cause additional complexity in tutorials / instructions. A good discussion for HackaTont2020_v2 to clarify which topics will be global and which will be in a robot namespace. We should do an inventory on all the topics and parameters used and agree on good practices in e.g. when to use private node handles or topic remapping.
